### ISSUE TITLE
Similar to BytecodeViewer?

### ISSUE THREAD

**Issue by theuserbl** [samczsun/Helios#1]
Currently you have no code or binaries published.
But it sounds a little bit like BytecodeViewer:
https://github.com/Konloch/bytecode-viewer

I think, that is something, which could be interesting for you.

**Comment by samczsun** [comment]
Yes, I was originally writing a bleeding edge fork of Bytecode Viewer, but I decided that it would be better to start from scratch. Granted, you'll see some files which look similar/are identical to those in the Bytecode Viewer repository, but that is because the code is still under my copyright. They just weren't committed under my name.
