### ISSUE TITLE
Enjarify version

### ISSUE THREAD

**Issue by Storyyeller** [samczsun/Helios#17]
I noticed you are using a commit hash for the Enjarify version. I thought I should point out that Enjarify follows semantic versioning now, in case you wanted to switch to that.

https://github.com/google/enjarify/releases

**Comment by samczsun** [comment]
Ahh, semantic versioning. I hope you don't mind me saying this, but I don't think in this particular case identifying based on semver will be more beneficial over commit hashes, and here's my logic behind it:

The biggest benefit to semvers, for those who didn't know and are reading, is that it helps prevent incompatibilities between builds. Say my API used a serialization library which changed formats between version 'a' and version 'b'. Because these formats are incompatible the library should bump the major version, which in turn should result in me bumping my major version as well. If one of us doesn't do that, then an end user/developer may update thinking it was compatible and then destroy everything.

The thing with Helios is that libraries are distributed along with the particular version and incompatibilities are worked out on a per-version basis. The benefit to this is that although authors likely can't release a patch on a per-commit basis I would much rather update to that new commit assuming it's not buggy (f.ex Krakatau went through quite a few commits and I was very excited to get that updated within Helios ASAP).

I suppose what I'm trying to say is that I really appreciate you letting me know, but I'm going to have to politely decline because I think commit-based dependency management would be better for this project.

However, if you think my logic is flawed I'm open to feedback. Otherwise I'll let you close the issue if you think this is resolved

**Comment by Storyyeller** [comment]
It's a fair point. I'm not planning to maintain multiple versions in parallel or backport fixes or anything like that either, so there's little benefit. The only real benefit is that it makes it easier to compare version strings.

**Comment by samczsun** [comment]
That is also a good point. I wonder if I can get the numerical ID of a commit. That'll be a nice and easy way of doing it
