### ISSUE TITLE
Option to show a different view by default?

### ISSUE THREAD

**Issue by Sponges** [samczsun/Helios#3]
Would be nice if there was an option to set it to always see `Text` or `Fernflower` when you click on a file instead of always viewing the Hex :)

**Comment by samczsun** [comment]
Hex is the default view because it is the one format (except for other formats like binary, octal, etc) in which all files can be accurately represented with no missing data. Plaintext would fail to render control codes and whatnot.

As more and more filetypes are supported, you would end up having so many different default options it would be easier just to Ctrl-T and select something.

**Comment by Sponges** [comment]
:ok_woman:

**Comment by Zbob750** [comment]
I can sort of understand the logic behind this decision. That it would be jarring to have different default views for different file types. But I most disagree. I've been using this to do my work for SpigotMC's Premium Resource section and having to continuously select the same decompiler for thousands of class files is not only annoying, it's frustrating and inconvenient.

I respectfully ask you reconsider this decision, and expose this in some way, even if it is basic and/or hidden.

**Comment by samczsun** [comment]
Very well. How do you envision selecting default decompilers and filetypes? If you have a preferred method I'll work with that. Otherwise I'll come up with something

**Comment by Zbob750** [comment]
I'm not terribly concerned with how it's implemented on your end. I certainly don't see any need to create some massive codebase around this feature. As far as I'm concerned it could be buried in the config file, loaded on startup, just mapping file extensions to some string for the preferred view.

Obviously that isn't terribly user-friendly. But there will always be time to make it prettier.

**Comment by Zbob750** [comment]
Thanks :+1:
