### ISSUE TITLE
Crash on linux (Mint 17.2)

### ISSUE THREAD

**Issue by null-dev** [samczsun/Helios#6]
I'm getting a native crash when attempting to start the JAR of the alpha build on a Linux system.

Here are some logs and system information:

Terminal Output:
http://files.nulldev.xyz/Misc/RandomStuff/terminal.txt

Native Crash Log:
http://files.nulldev.xyz/Misc/RandomStuff/hs_err_pid9753.log

System Information:
http://files.nulldev.xyz/Misc/RandomStuff/SystemInfo-Inspiron15RMint.jpg

**Comment by theuserbl** [comment]
Same thing on Knoppix. There it loads the 32bit system. So there are 32bit addesses mentioned. But same error output.
Thats the problem, if people using - for what reason ever - SWT instead of Swing or AWT.

If a program is written with Swing, it runs everywhere, where Java is installed. The native Java-dependencies on Linux/Unix for the GUI is only Motif. And that comes with Java itself. So it needs only X11. SWT on the other side, needs a special version of GTK+, which is _not_ included in the SWT-package.

Normally there exiting one big rule for Java-programs: Let the native-parts as less as possible.
For the GUI you don't need any native parts, because of Swing.
You only need them, if you want - for example - to create games using OpenGL, then you have to use libraries like jogl, which using native code.
But there is also the disadvantage, that the programs then only run on all platforms, for which the right native libs are added. But for using OpenGL you have no other option, then going that way.
